# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
# code: language=ansible
---
- name: Apt update cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  
- name: "Create application directory {{ influxdb_path }}"
  become: true
  ansible.builtin.file:
    path: "{{ influxdb_path }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Deploy influxdb environment"
  ansible.builtin.template:
    src:  "influxdb.env"
    dest: "{{ influxdb_path }}/influxdb.env"

- name: "Create influxdb persistent configuration directory"
  become: true
  ansible.builtin.file:
    path: "{{ influxdb_path }}/config"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: "Docker volume create '{{ deployment }}-influxdb-data'"
  community.docker.docker_volume:
    name: "{{ deployment }}-influxdb-data"

- name: Docker network create '{{ influxdb_docker_network }}'
  when: influxdb_docker_network != 'host'
  community.docker.docker_network:
    name: "{{ influxdb_docker_network }}"

- name: Docker pull influxdb:{{ influxdb_version }}
  community.docker.docker_image:
    name: influxdb
    tag: "{{ influxdb_version }}"
    source: pull

- name: "Start docker container {{ deployment }}-influxdb"
  community.docker.docker_container:
    name: "{{ deployment }}-influxdb"
    image: influxdb:{{ influxdb_version }}
    hostname: "{{ deployment }}-influxdb"
    networks:
      - name: "{{ influxdb_docker_network }}"
    restart_policy: unless-stopped
    ports:
      - "8086:8086/tcp"
    env_file: "{{ influxdb_path }}/influxdb.env"
    volumes:
      - "{{ deployment }}-influxdb-data:/var/lib/influxdb2"
      - "{{ influxdb_path }}/config:/etc/influxdb2"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
